# Generated by Django 6.1.1 on 2026-09-11 21:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('DEF', 'Defensor'), ('MEI', 'Meio-campista'), ('ATA', 'Atacante')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('12'))], verbose_name='valor em Portal Coins')),
                ('status', models.CharField(choices=[('provavel', 'Provável'), ('duvida', 'Dúvida'), ('lesionado', 'Lesionado'), ('suspenso', 'Suspenso')], default='provavel', max_length=12)),
                ('noticia_url', models.URLField(blank=True, max_length=500, verbose_name='link da notícia que justifica o status')),
                ('apelidos', models.CharField(blank=True, help_text='Como o jogador aparece nas manchetes. Ex.: Léo, Léo Índio', max_length=200, verbose_name='apelidos separados por vírgula')),
                ('no_elenco', models.BooleanField(default=True, help_text='Desmarque quando o jogador deixar o Náutico. Ele para de pontuar, congela de valor e some do mercado.', verbose_name='ainda está no clube')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID na API-Football')),
            ],
            options={
                'verbose_name_plural': 'jogadores',
                'ordering': ['posicao', '-valor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('adversario', models.CharField(max_length=60)),
                ('mando', models.CharField(choices=[('casa', 'Em casa'), ('fora', 'Fora')], default='casa', max_length=4)),
                ('data_jogo', models.DateTimeField(verbose_name='data e hora do jogo')),
                ('gols_sofridos', models.PositiveIntegerField(blank=True, help_text='Preencha depois do jogo. É o que define o clean sheet.', null=True, verbose_name='gols sofridos pelo Náutico')),
                ('processada', models.BooleanField(default=False)),
                ('api_fixture_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID da partida na API-Football')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moedas', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6, verbose_name='Portal Coins livres')),
                ('pontos_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('time_nome', models.CharField(blank=True, max_length=40, verbose_name='nome do time')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pontos_total'],
            },
        ),
        migrations.CreateModel(
            name='Escalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('custo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='custo no momento em que foi salva')),
                ('criada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes', to=settings.AUTH_USER_MODEL)),
                ('jogadores', models.ManyToManyField(related_name='escalacoes', to='core.jogador')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalacoes', to='core.rodada')),
            ],
            options={
                'verbose_name_plural': 'escalações',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rodada'), name='uma_escalacao_por_rodada')],
            },
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou_em_campo', models.BooleanField(default=False, help_text='Desmarcado = ficou no banco: 0,0 ponto e valor congelado.')),
                ('gols', models.PositiveSmallIntegerField(default=0)),
                ('assistencias', models.PositiveSmallIntegerField(default=0)),
                ('desarmes', models.PositiveSmallIntegerField(default=0, verbose_name='desarmes e interceptações')),
                ('finalizacoes_no_gol', models.PositiveSmallIntegerField(default=0)),
                ('finalizacoes_na_trave', models.PositiveSmallIntegerField(default=0)),
                ('finalizacoes_fora', models.PositiveSmallIntegerField(default=0, verbose_name='finalizações para fora ou bloqueadas')),
                ('dribles', models.PositiveSmallIntegerField(default=0)),
                ('faltas_sofridas', models.PositiveSmallIntegerField(default=0)),
                ('faltas_cometidas', models.PositiveSmallIntegerField(default=0)),
                ('penaltis_sofridos', models.PositiveSmallIntegerField(default=0)),
                ('penaltis_cometidos', models.PositiveSmallIntegerField(default=0)),
                ('penaltis_perdidos', models.PositiveSmallIntegerField(default=0)),
                ('gols_contra', models.PositiveSmallIntegerField(default=0)),
                ('cartoes_amarelos', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('cartao_vermelho', models.CharField(choices=[('nenhum', 'Não foi expulso'), ('direto', 'Vermelho direto'), ('segundo_amarelo', 'Expulso pelo segundo amarelo')], default='nenhum', max_length=16)),
                ('defesas_dentro_area', models.PositiveSmallIntegerField(default=0, verbose_name='defesas dentro da área')),
                ('defesas_fora_area', models.PositiveSmallIntegerField(default=0, verbose_name='defesas fora da área')),
                ('penaltis_defendidos', models.PositiveSmallIntegerField(default=0)),
                ('conferido', models.BooleanField(default=False, help_text='Marque depois de conferir os dados importados da API.')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='core.jogador')),
                ('rodada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouts', to='core.rodada')),
            ],
            options={
                'verbose_name_plural': 'scouts',
                'constraints': [models.UniqueConstraint(fields=('jogador', 'rodada'), name='um_scout_por_jogador_por_rodada')],
            },
        ),
    ]
