# Generated by Django 6.1.1 on 2026-09-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='api_fixture_id',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Deixe em branco se você preenche os scouts à mão. Só é usado para importar os scouts da API.', null=True, verbose_name='ID da partida na API-Football'),
        ),
    ]
